{
 "title": "AWS EC2 Instances",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "name",
    "query": "ec2_instance_attribute(us-east-1, Tags.Name, {})"
   },
   {
    "name": "instance_id",
    "query": "ec2_instance_attribute(us-east-1, InstanceId, { \"tag:Name\": [\"$name\"] })"
   }
  ]
 },
 "panels": [
  {
   "title": "CPUUtilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{InstanceId}}",
     "dimensions": { "InstanceId": "$instance_id" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "period": "300",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "CPUCreditBalance",
   "type": "graph",
   "description": "CPU credits are only used on burstable instance types",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "{{InstanceId}}",
     "dimensions": { "InstanceId": "$instance_id" },
     "metricName": "CPUCreditBalance",
     "namespace": "AWS/EC2",
     "period": "300",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "Memory metrics are only available for storm services that opt into additional cloudwatch metrics",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "{{InstanceId}}_used",
     "dimensions": { "InstanceId": "$instance_id" },
     "metricName": "mem_used",
     "namespace": "CWAgent",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    },
    {
     "alias": "{{InstanceId}}_total",
     "dimensions": { "InstanceId": "$instance_id" },
     "metricName": "mem_total",
     "namespace": "CWAgent",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Disk Storage",
   "type": "graph",
   "description": "Disk storage metrics are only available for storm services that opt into additional cloudwatch metrics",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{InstanceId}}",
     "dimensions": { "InstanceId": "$instance_id" },
     "metricName": "storage",
     "namespace": "CustomCloudwatchMetrics",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "TCP Connections",
   "type": "graph",
   "description": "TCP connection count metrics are only available for storm services that opt into additional cloudwatch metrics",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{InstanceId}}",
     "dimensions": { "InstanceId": "$instance_id" },
     "metricName": "netstat_tcp_established",
     "namespace": "CWAgent",
     "region": "us-east-1",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "NetworkIn",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "alias": "{{label}}",
     "expression": "inbound / 300",
     "period": "300",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "NetworkOut",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "alias": "{{label}}",
     "expression": "outbound / 300",
     "period": "300",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    }
   ]
  }
 ]
}