{
 "title": "AWS ELB",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "elb",
    "query": "dimension_values(us-east-1, AWS/ELB, HealthyHostCount, LoadBalancerName)"
   }
  ]
 },
 "panels": [
  {
   "title": "HealthyHostCount",
   "type": "timeseries",
   "description": "The number of healthy instances registered with your load balancer. A newly registered instance is considered healthy after it passes the first health check. If cross-zone load balancing is enabled, the number of healthy instances for the LoadBalancerName dimension is calculated across all Availability Zones. Otherwise, it is calculated per Availability Zone.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "{{LoadBalancerName}} min",
     "dimensions": { "LoadBalancerName": "$elb" },
     "metricName": "HealthyHostCount",
     "namespace": "AWS/ELB",
     "region": "default",
     "statistics": [ "Minimum" ]
    },
    {
     "alias": "{{LoadBalancerName}} avg",
     "dimensions": { "LoadBalancerName": "$elb" },
     "metricName": "HealthyHostCount",
     "namespace": "AWS/ELB",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "alias": "{{LoadBalancerName}} max",
     "dimensions": { "LoadBalancerName": "$elb" },
     "metricName": "HealthyHostCount",
     "namespace": "AWS/ELB",
     "region": "default",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "UnHealthyHostCount",
   "type": "timeseries",
   "description": "The number of unhealthy instances registered with your load balancer. An instance is considered unhealthy after it exceeds the unhealthy threshold configured for health checks. An unhealthy instance is considered healthy again after it meets the healthy threshold configured for health checks.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "{{LoadBalancerName}} min",
     "dimensions": { "LoadBalancerName": "$elb" },
     "metricName": "UnHealthyHostCount",
     "namespace": "AWS/ELB",
     "region": "default",
     "statistics": [ "Minimum" ]
    },
    {
     "alias": "{{LoadBalancerName}} avg",
     "dimensions": { "LoadBalancerName": "$elb" },
     "metricName": "UnHealthyHostCount",
     "namespace": "AWS/ELB",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "alias": "{{LoadBalancerName}} max",
     "dimensions": { "LoadBalancerName": "$elb" },
     "metricName": "UnHealthyHostCount",
     "namespace": "AWS/ELB",
     "region": "default",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "description": "[HTTP listener] The total time elapsed, in seconds, from the time the load balancer sent the request to a registered instance until the instance started to send the response headers.\n\n[TCP listener] The total time elapsed, in seconds, for the load balancer to successfully establish a connection to a registered instance.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "{{LoadBalancerName}} average",
     "dimensions": { "LoadBalancerName": "$elb" },
     "metricName": "Latency",
     "namespace": "AWS/ELB",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "alias": "{{LoadBalancerName}} max",
     "dimensions": { "LoadBalancerName": "$elb" },
     "metricName": "Latency",
     "namespace": "AWS/ELB",
     "region": "default",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "RequestCount",
   "type": "timeseries",
   "description": "The number of requests completed or connections made during the specified interval (1 or 5 minutes).\n\n[HTTP listener] The number of requests received and routed, including HTTP error responses from the registered instances.\n\n[TCP listener] The number of connections made to the registered instances.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "{{LoadBalancerName}} sum",
     "dimensions": { "LoadBalancerName": "$elb" },
     "metricName": "RequestCount",
     "namespace": "AWS/ELB",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "SurgeQueueCount",
   "type": "timeseries",
   "description": "The total number of requests (HTTP listener) or connections (TCP listener) that are pending routing to a healthy instance. The maximum size of the queue is 1,024. Additional requests or connections are rejected when the queue is full. For more information, see SpilloverCount.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "{{LoadBalancerName}} max",
     "dimensions": { "LoadBalancerName": "$elb" },
     "metricName": "SurgeQueueLength",
     "namespace": "AWS/ELB",
     "region": "default",
     "statistics": [ "Maximum" ]
    },
    {
     "alias": "{{LoadBalancerName}} avg",
     "dimensions": { "LoadBalancerName": "$elb" },
     "metricName": "SurgeQueueLength",
     "namespace": "AWS/ELB",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "SpilloverCount",
   "type": "timeseries",
   "description": "The total number of requests that were rejected because the surge queue is full.\n\n[HTTP listener] The load balancer returns an HTTP 503 error code.\n\n[TCP listener] The load balancer closes the connection.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "{{LoadBalancerName}} sum",
     "dimensions": { "LoadBalancerName": "$elb" },
     "metricName": "SpilloverCount",
     "namespace": "AWS/ELB",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "HTTPCode_Backend_5XX",
   "type": "timeseries",
   "description": "[HTTP listener] The number of HTTP response codes generated by registered instances. This count does not include any response codes generated by the load balancer.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "{{LoadBalancerName}} sum",
     "dimensions": { "LoadBalancerName": "$elb" },
     "metricName": "HTTPCode_Backend_5XX",
     "namespace": "AWS/ELB",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "HTTPCode_ELB_5XX",
   "type": "timeseries",
   "description": "[HTTP listener] The number of HTTP 5XX server error codes generated by the load balancer. This count does not include any response codes generated by the registered instances. The metric is reported if there are no healthy instances registered to the load balancer, or if the request rate exceeds the capacity of the instances (spillover) or the load balancer.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "{{LoadBalancerName}} sum",
     "dimensions": { "LoadBalancerName": "$elb" },
     "metricName": "HTTPCode_ELB_5XX",
     "namespace": "AWS/ELB",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  }
 ]
}