{
 "title": "AWS Lambda",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "lambda",
    "query": "dimension_values(us-east-1, AWS/Lambda, Invocations , FunctionName)"
   }
  ]
 },
 "panels": [
  { "title": "Individual Lambda Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Invocations",
   "type": "timeseries",
   "description": "Invocations – The number of times your function code is executed, including successful executions and executions that result in a function error. Invocations aren't recorded if the invocation request is throttled or otherwise resulted in an invocation error. This equals the number of requests billed.\n\nErrors – The number of invocations that result in a function error. Function errors include exceptions thrown by your code and exceptions thrown by the Lambda runtime. The runtime returns errors for issues such as timeouts and configuration errors. To calculate the error rate, divide the value of Errors by the value of Invocations. Note that the timestamp on an error metric reflects when the function was invoked, not when the error occurred.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "dimensions": { "FunctionName": "$lambda" },
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Sum"
    },
    {
     "dimensions": { "FunctionName": "$lambda" },
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Error rate [errors/invocations]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "error rate",
     "expression": "errors / invocations",
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Peformance",
   "type": "timeseries",
   "description": "Duration – The amount of time that your function code spends processing an event. The billed duration for an invocation is the value of Duration rounded up to the nearest millisecond.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "FunctionName": "$lambda" },
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    },
    {
     "dimensions": { "FunctionName": "$lambda" },
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expression": "filter @type = \"REPORT\"\n| stats max(@memorySize / 1024 / 1024) as AllocatedMemory,\n    avg(@maxMemoryUsed / 1024 / 1024) as AverageMemoryUsed by bin(5m)",
     "logGroupNames": [ "/aws/lambda/$lambda" ],
     "namespace": "AWS/Lambda",
     "queryMode": "Logs",
     "region": "us-east-1",
     "statsGroups": [ "bin(5m)" ]
    }
   ]
  },
  {
   "title": "Global Lambda Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total invocations",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
     "targets": [
      { "metricName": "Invocations", "namespace": "AWS/Lambda", "region": "us-east-1", "statistic": "Sum" }
     ]
    },
    {
     "title": "Total error rate [errors/invocations]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
     "targets": [
      { "expression": "errors / invocations", "metricEditorMode": 1, "region": "default", "statistic": "Average" }
     ]
    },
    {
     "title": "Total throttle rate [throttles/invocations]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
     "targets": [
      { "expression": "throttles / invocations", "metricEditorMode": 1, "region": "default", "statistic": "Average" }
     ]
    }
   ]
  }
 ]
}