{
 "title": "AWS RDS",
 "description": "Visualize Amazon RDS metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance_id",
    "query": "dimension_values(us-east-1, AWS/RDS, CPUUtilization, DBInstanceIdentifier)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU utilization per instance [%]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{DBInstanceIdentifier}}",
     "dimensions": { "DBInstanceIdentifier": "$instance_id" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Database connections [count sum]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{DBInstanceIdentifier}}",
     "dimensions": { "DBInstanceIdentifier": "$instance_id" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Available storage space [bytes]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "{{DBInstanceIdentifier}}",
     "dimensions": { "DBInstanceIdentifier": "$instance_id" },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/RDS",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Available RAM [bytes]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "{{DBInstanceIdentifier}}",
     "dimensions": { "DBInstanceIdentifier": "$instance_id" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Read throughput [bytes/sec]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "{{DBInstanceIdentifier}}",
     "dimensions": { "DBInstanceIdentifier": "$instance_id" },
     "metricName": "ReadThroughput",
     "namespace": "AWS/RDS",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Write throughput [bytes/sec]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "{{DBInstanceIdentifier}}",
     "dimensions": { "DBInstanceIdentifier": "$instance_id" },
     "metricName": "WriteThroughput",
     "namespace": "AWS/RDS",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Read Latency [sec]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "alias": "{{DBInstanceIdentifier}}",
     "dimensions": { "DBInstanceIdentifier": "$instance_id" },
     "metricName": "ReadLatency",
     "namespace": "AWS/RDS",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Write latency [sec]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "{{DBInstanceIdentifier}}",
     "dimensions": { "DBInstanceIdentifier": "$instance_id" },
     "metricName": "WriteLatency",
     "namespace": "AWS/RDS",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Read operations [IOPS]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "{{DBInstanceIdentifier}}",
     "dimensions": { "DBInstanceIdentifier": "$instance_id" },
     "metricName": "ReadIOPS",
     "namespace": "AWS/RDS",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Write operations [IOPS]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "{{DBInstanceIdentifier}}",
     "dimensions": { "DBInstanceIdentifier": "$instance_id" },
     "metricName": "WriteIOPS",
     "namespace": "AWS/RDS",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Replica Lag [sec]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "{{DBInstanceIdentifier}}",
     "dimensions": { "DBInstanceIdentifier": "$instance_id" },
     "metricName": "ReplicaLag",
     "namespace": "AWS/RDS",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Transaction Log Disk Usage [bytes]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "{{DBInstanceIdentifier}}",
     "dimensions": { "DBInstanceIdentifier": "$instance_id" },
     "metricName": "TransactionLogsDiskUsage",
     "namespace": "AWS/RDS",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Swap Usage [bytes]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "{{DBInstanceIdentifier}}",
     "dimensions": { "DBInstanceIdentifier": "$instance_id" },
     "metricName": "SwapUsage",
     "namespace": "AWS/RDS",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Maximum Used Transacations IDs [count sum]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{DBInstanceIdentifier}}",
     "dimensions": { "DBInstanceIdentifier": "$instance_id" },
     "metricName": "MaximumUsedTransactionIDs",
     "namespace": "AWS/RDS",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    }
   ]
  }
 ]
}